import Head from 'next/head'
import Chat from "./Chat";
import Output from "./Output"
import { useState } from "react";

export default function Home() {

  const [text, setMyText] = useState('')
  const [isPending, setIsPending] = useState(false)
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home">
           <div className="header masked-copy texture-orange big-type">
                <h2> Atlas </h2>
                <p>
                    Let's talk about your goals. I'll figure out the rest.
                </p>
            </div> 
            <Chat text = {text} setMyText = {setMyText} setIsPending = {setIsPending}></Chat>
            <Output text = {text} isPending = {isPending} setIsPending = {setIsPending}></Output>
        </div>
    </>
  )
}
